dist: trusty
language: node_js
node_js:
- '6'
install:
- npm install
script:
- npm run build
deploy:
  provider: s3
  access_key_id: AKIAZCZ5UOG53H5DITDL
  secret_access_key:
    secure: bgSbNrKMbpKqUBN8T17cwU5vbhgq4QLbipqo1PglHhSZnzX1X6NXJevAKWOIVP9bOTFADtQpaszTrHjfuzDx2veUnQxHm1r00hmhzgOZarVqYklTNIxSbLQAB7MiqL03iArGTSNLNagGi/IhNL4M8kwrfnqLKlKSfMJ30BkIkQinqpbX6LVi/Pd0Ftgb9iDskXoq1ggx3kMEixeShR+YrNyUZqoSVQ/kAB4uqC25OF7Hv8IBB3BxsFYEBcGx3Zmt3juKDAQU3rPO1phZgGJMJgs+3Etgd20zhn8wdXHhJ3oGcOmboQm4yb4yyDJhMycrfVEJqUMq0X1+U1OJ3nf42HkdmEB2m1b6Wlr6N3j1yGJYd/QhuwsmzY0YwGG2aUEgIMyW8sSCmrkXREIjYaNOBM5wfLDsBlrn4XboQgn6XSlcRadnSfCaBJwtOPnTXiU95i0+5qlIIac6ecSKEDFsjYkLHTHEwM6Vk/7gNQK3FSCSta5BFppfqKhSdwoEnQnFydoYihd5Jl97Af6kMPF9L2LSodXBm8XZSUKDPieMC3zJT6LP62xLe1s+JSYDA/6DcOL7fkqlmGzFM4w/vDVekPRyxnDUI1+OkgVJVmw18W50WGDoDAFsfDbmrzWpuNTWMLcWKbsKTXAeDPJp/IL6cejnxbTFLdaYiuxG9Ru0yPs=
  bucket: drrotzandassociates.com
  local-dir: build
  acl: public_read
  skip_cleanup: true
  on:
    repo: 9oh9/drbarryrotz
