dist: trusty
language: node_js
node_js:
- '6'
install:
- npm install
script:
- npm run build
deploy:
  provider: s3
  access_key_id: AKIAJFEDO7VSBAUQ6EZQ
  secret_access_key:
    secure: YfMs0Gurd1ghyJ9KpfatUJr7kAAAW82JaQAXougny4v7f6MFGPNHdutBa58dz5AeE6BND9DdcAhqlVsRmELQE/8ycns3ka70ScWBxdij96xOaU9onVIcNWf8t0uTkf3kqo98lHY8wl2DTPS2LFqLjs0XFFBk8KXrcxCukqHcofM+ZuN0KbtGsDlg1XCKnhzBl8I9bQ986KD928jAY18w5YiMpzvLAzx+7o+3TaY4GkjlMRfLK3UlQ3V6gqfp0PlMwatT+5TaxL8ITlwlOhgrjbd4NZoLNNLhiUmMNfj+VrTfA5deH+gCggzPs/QkclvxdNbhxPS8U21dPxP4ZjB1//DuGxzClJITt8/RiPkFCT/Haq7xEvwLgQh08QZDxlEiHt/TUDCpFHwSjh/UEQiFDsoZxzr+soNPRnL7Kbd25fRmaJuCvsPGO/Xjf/zu77BcZWlJTrs2OUkQTqgejChyX3NVXBTxiptHXIVLp4zgCxjbgqEdhzZYUcs1TQmLT8pKRs4c3dzVF3HPDot75JUw30NmCD2YmEZm+FsvmJU0wJmArS2lBKNzaSl90FUzieJRfflOsJr9xxY1PPsMpFapr1xlZFIpxb80YJ9IMLxau7hoICoNlLXMqKpkX70M4bxngWTcdTCCIp57+lmU+Ege7FUomn/kspaG3SDol/2ehjA=
  bucket: drrotzandassociates.com
  local-dir: build
  acl: public_read
  skip_cleanup: true
  on:
    repo: 9oh9/drbarryrotz
